---
# repository defaults
wavefront_proxy_repo_url: "https://packagecloud.io/wavefront/proxy"
wavefront_repo_gpgkey: "https://packagecloud.io/wavefront/proxy/gpgkey"
wavefront_rpm_repo_url: "https://packagecloud.io/wavefront/proxy/el"
wavefront_config_dir: '/etc/wavefront'
wavefront_config: "{{ wavefront_config_dir }}/tsconfig.json"
wavefront_proxy_pkg: ""
# proxy settings
wavefront_proxy_port: "2878"
wavefront_proxy_opentsdb_ports: "4242"
wavefront_proxy_json_ports: ~
wavefront_proxy_writeHttpJson_ports: ~
wavefront_proxy_histogram_enabled: true
#
# Histogram settings
#
# - minute aggregation:
histogramMinuteListenerPorts: 40001
histogramMinuteAccumulators: 2
histogramMinuteFlushSecs: 70
# - hour aggregation:
histogramHourListenerPorts: 40002
histogramHourAccumulators: 2
histogramHourFlushSecs: 4200
# - day aggregation:
histogramDayListenerPorts: 40003
histogramDayAccumulators: 2
histogramDayFlushSecs: 18000
# - distribution format:
histogramDistListenerPorts: 40000
histogramDistAccumulators: 2
histogramDistFlushSecs: 70
histogramReceiveBufferFlushInterval: 500
histogramProcessingQueueScanInterval: 100
histogramPersistMessages: "false"
traceListenerListenerPorts: 30000
deltaCounterPort: 50000
