---

- block:
  - name: create telegraf script dir
    file:
      path: "{{ telegraf_script_dir }}"
      owner: root
      group: root
      mode: 0755
      state: directory

  - name: plumb default telegraf.conf
    template: src="telegraf.conf.j2" dest="{{ telegraf_main_config }}" mode=0644
    notify: restart telegraf

  - name: plumb default wavefront output plugin
    template: src="10-wavefront.conf.j2" dest="{{ telegraf_additional_config_dir }}/10-wavefront.conf" mode=0644
    notify: restart telegraf

  - name: telegraf custom scripts
    template: src="scripts/{{ item }}.j2" dest="{{ telegraf_script_dir }}/{{ item }}" mode=0755
    with_items:
      - "kernel-version.sh"
      - "os-version.sh"

  - name: telegraf kernel and os version
    template: src="input-kernel-version.conf.j2" dest="{{ telegraf_additional_config_dir }}/kernel-version.conf" mode=0644
    notify: restart telegraf

  - name: telegraf input - netstat.sh
    template: src="scripts/netstat.sh" dest="{{ telegraf_script_dir }}/netstat.sh" mode=0755

  - name: Pause for 30 seconds
    pause:
      seconds: 30

  - name: telegraf input - input-exec-netstat.conf
    template: src="input-exec-netstat.conf.j2" dest="{{ telegraf_additional_config_dir }}/input-exec-netstat.conf" mode=0644
    notify: restart telegraf

  tags:
   - telegraf
   - configure-telegraf
